disable_motion_planning: false
approach_planner:

  planning_groups: # Sorted by order of preference
    - left_arm
    - right_arm
    - left_arm_and_torso
    - right_arm_and_torso
    - whole_body

  exclude_from_planning_joints:
    - head_pan_joint
    - head_tilt_joint

  joint_tolerance: 0.01
  skip_planning_approach_vel: 0.5
  skip_planning_approach_min_dur: 0.5
